[build-system]
requires = ["maturin>=0.13,<0.14"]
build-backend = "maturin"

[project]
name = "tantivy"
requires-python = ">=3.7"

[project.optional-dependencies]
dev = [
    "nox",
]

[tool.maturin]
bindings = "pyo3"
